const Salles = [
    {
        room: "C304",
        size: "151",
        seats: "150",
        floor: "3",
    },
    {
        room: "B304",
        size: "67",
        seats: "60",
        floor: "3",
    },
    {
        room: "B305",
        size: "67",
        seats: "48",
        floor: "3",
    },
    {
        room: "C401",
        size: "92",
        seats: "60",
        floor: "4",
    },
    {
        room: "C402",
        size: "96",
        seats: "60",
        floor: "4",
    },
    {
        room: "C403",
        size: "63",
        seats: "44",
        floor: "4",
    },
    {
        room: "C404",
        size: "63",
        seats: "44",
        floor: "4",
    },
    {
        room: "C405",
        size: "88",
        seats: "60",
        floor: "4",
    },
    {
        room: "C406",
        size: "84",
        seats: "48",
        floor: "4",
    },
    {
        room: "B506",
        size: "92",
        seats: "84",
        floor: "4",
    },
    {
        room: "B505",
        size: "43",
        seats: "30",
        floor: "4",
    },
    {
        room: "B503",
        size: "48",
        seats: "22",
        floor: "4",
    },
    {
        room: "B502",
        size: "33",
        seats: "12",
        floor: "4",
    },
    {
        room: "B501",
        size: "33",
        seats: "12",
        floor: "4",
    },
    {
        room: "A412",
        size: "48",
        seats: "20",
        floor: "4",
    },
    {
        room: "A411",
        size: "50",
        seats: "16",
        floor: "4",
    },
    {
        room: "A410",
        size: "22",
        seats: "8",
        floor: "4",
    },
    {
        room: "A408",
        size: "100",
        seats: "42",
        floor: "4",
    },
    {
        room: "A621",
        size: "23",
        seats: "18",
        floor: "6",
    },
    {
        room: "A622",
        size: "30",
        seats: "20",
        floor: "6",
    },
    {
        room: "A624",
        size: "18",
        seats: "10",
        floor: "6",
    },
    {
        room: "A625",
        size: "14",
        seats: "8",
        floor: "6",
    },
    {
        room: "A811",
        size: "50",
        seats: "40",
        floor: "8",
    },
    {
        room: "A812",
        size: "33",
        seats: "20",
        floor: "8",
    },
    {
        room: "A813",
        size: "31",
        seats: "20",
        floor: "8",
    },
    {
        room: "A814",
        size: "33",
        seats: "20",
        floor: "8",
    },
    {
        room: "A815",
        size: "33",
        seats: "20",
        floor: "8",
    },
    {
        room: "A816",
        size: "50",
        seats: "36",
        floor: "8",
    },
    {
        room: "B801",
        size: "22",
        seats: "16",
        floor: "8",
    },
    {
        room: "B802",
        size: "69",
        seats: "60",
        floor: "8",
    },
    {
        room: "B803",
        size: "58",
        seats: "48",
        floor: "8",
    },
    {
        room: "B804",
        size: "60",
        seats: "48",
        floor: "8",
    },
    {
        room: "A903",
        size: "33",
        seats: "28",
        floor: "9",
    },
    {
        room: "A906",
        size: "33",
        seats: "28",
        floor: "9",
    },
    {
        room: "A913",
        size: "47",
        seats: "24",
        floor: "9",
    },
    {
        room: "A918",
        size: "33",
        seats: "28",
        floor: "9",
    },
    {
        room: "A919",
        size: "71",
        seats: "48",
        floor: "9",
    },
    {
        room: "C953",
        size: "55",
        seats: "25",
        floor: "9",
    },
    {
        room: "C954",
        size: "50",
        seats: "25",
        floor: "9",
    },
    {
        room: "C955",
        size: "58",
        seats: "38",
        floor: "9",
    },
    {
        room: "C956",
        size: "73",
        seats: "48",
        floor: "9",
    },
];

module.exports = Salles;
